// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: split.proto

package splitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request
type SplitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SplitReq) Reset() {
	*x = SplitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitReq) ProtoMessage() {}

func (x *SplitReq) ProtoReflect() protoreflect.Message {
	mi := &file_split_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitReq.ProtoReflect.Descriptor instead.
func (*SplitReq) Descriptor() ([]byte, []int) {
	return file_split_proto_rawDescGZIP(), []int{0}
}

func (x *SplitReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// response
type SplitRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []string `protobuf:"bytes,8,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *SplitRes) Reset() {
	*x = SplitRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRes) ProtoMessage() {}

func (x *SplitRes) ProtoReflect() protoreflect.Message {
	mi := &file_split_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRes.ProtoReflect.Descriptor instead.
func (*SplitRes) Descriptor() ([]byte, []int) {
	return file_split_proto_rawDescGZIP(), []int{1}
}

func (x *SplitRes) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_split_proto protoreflect.FileDescriptor

var file_split_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x08, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x45, 0x0a,
	0x0c, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a,
	0x05, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_split_proto_rawDescOnce sync.Once
	file_split_proto_rawDescData = file_split_proto_rawDesc
)

func file_split_proto_rawDescGZIP() []byte {
	file_split_proto_rawDescOnce.Do(func() {
		file_split_proto_rawDescData = protoimpl.X.CompressGZIP(file_split_proto_rawDescData)
	})
	return file_split_proto_rawDescData
}

var file_split_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_split_proto_goTypes = []interface{}{
	(*SplitReq)(nil), // 0: protofiles.SplitReq
	(*SplitRes)(nil), // 1: protofiles.SplitRes
}
var file_split_proto_depIdxs = []int32{
	0, // 0: protofiles.SplitService.Split:input_type -> protofiles.SplitReq
	1, // 1: protofiles.SplitService.Split:output_type -> protofiles.SplitRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_split_proto_init() }
func file_split_proto_init() {
	if File_split_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_split_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_split_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_split_proto_goTypes,
		DependencyIndexes: file_split_proto_depIdxs,
		MessageInfos:      file_split_proto_msgTypes,
	}.Build()
	File_split_proto = out.File
	file_split_proto_rawDesc = nil
	file_split_proto_goTypes = nil
	file_split_proto_depIdxs = nil
}
